# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create([
  { :name => "PeaceAndLoveLoveAndPeace", :password_digest => "$2a$10$NbyVQRbzRDPulfGVhUVxaOnl3rmvH.uE9/.BKYG2/g3pWVwk.O0y6", :token => "RIGVwblo_itHcyOcg768tg", :created_at => "2014-01-16 19:33:29", :updated_at => "2014-01-16 19:45:40", :gender => "M", :orientation => "Straight", :age => 73, :photo_file_name => "RingoStarr.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 58749, :photo_updated_at => "2014-01-16 19:33:28", :latitude => 37.853873, :longitude => -122.266295, :address => "3033-3041 Shattuck Avenue, Berkeley, CA 94705, USA" },
  { :name => "KiranHelferty", :password_digest => "$2a$10$Os2jkkG2IKGLKReKTt//eOgibYWMF.UaJkLczfD622gorFkR1oIz2", :token => "w2t70286fQ_vcwA7SzZg9g", :created_at => "2014-01-16 11:56:15", :updated_at => "2014-01-16 15:38:32", :gender => "M", :orientation => "Straight", :age => 28, :photo_file_name => "kiran-helferty.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 121838, :photo_updated_at => "2014-01-16 11:56:13", :latitude => 40.811164, :longitude => -73.952539, :address => "301 Saint Nicholas Avenue, New York, NY 10027, USA" },
  { :name => "MeanMrMustard", :password_digest => "$2a$10$dIS9tR3u3ARU..ANicOixew3d40yflMdGtJiVHnl4Iu8a6oPv/WCG", :token => "7K8C25oijm2fT5CVC6TmMw", :created_at => "2014-01-16 13:43:32", :updated_at => "2014-01-16 15:44:29", :gender => "M", :orientation => "Straight", :age => 73, :photo_file_name => "lennon.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 98127, :photo_updated_at => "2014-01-16 13:43:29", :latitude => 40.776012, :longitude => -73.969595, :address => "271 W 71st St, New York, NY 10023, USA" },
  { :name => "RockyRaccoon", :password_digest => "$2a$10$m6S9SDeBmTNsamvN8sHhfeqUwUEGKFREshY7nclYq6vTQd0JuLCDi", :token => "AKRe32QcpHGQgXNOr3Vyzg", :created_at => "2014-01-16 18:49:51", :updated_at => "2014-01-16 19:03:52", :gender => "M", :orientation => "Straight", :age => 71, :photo_file_name => "Paul_McCartney_1_.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 89860, :photo_updated_at => "2014-01-16 18:49:48", :latitude => 53.406244, :longitude => -2.987972, :address => "10 Mathew Street, Liverpool, Merseyside L2 6RE, UK" },
  { :name => "AllThingsMustPass", :password_digest => "$2a$10$pQ5X2XYxpe/rTBDWbXTnJOYw5BcXKSwiZEO0wj6EpMqt40IonCqHu", :token => "XbZ6iiZui5iLh2uti4Suow", :created_at => "2014-01-16 19:09:27", :updated_at => "2014-01-16 19:22:41", :gender => "M", :orientation => "Straight", :age => 70, :photo_file_name => "george-harrison-10.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 37863, :photo_updated_at => "2014-01-16 19:09:26", :latitude => 51.540149, :longitude => -0.914885, :address => "5 Parkside, Henley-on-Thames, Oxfordshire RG9 1TX, UK" },
  { :name => "ProspectiveEmployer", :password_digest => "$2a$10$ZYigIbW2zIfwjpCkd3S0cOJCh4SqM3jM/i8q75WQ0NtiUzb.BHCoq", :token => "xL3pw5XPk9_5LnXqTCF70g", :created_at => "2014-01-16 13:23:51", :updated_at => "2014-01-16 19:31:15", :gender => "F", :orientation => "Bisexual", :age => 30, :photo_file_name => "master-COOP354.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 421098, :photo_updated_at => "2014-01-16 13:23:48", :latitude => 40.7308593, :longitude => -73.9921641, :address => "756-770 Broadway, New York, NY 10003, USA" }
], :without_protection => true )

Profile.create([
  { :user_id => 1, :location => nil, :summary => "I'm a web developer who you are hopefully about to hire. I created this site. Things I like in addition to coding include but are by no means limited to ineptly playing the guitar, cats, improvisational and stand-up comedy, the NBA (go Raptors), Korean BBQ, scuba diving, the works of William Gibson, and haphazardly chosen lists.\r\n\r\nI am generally not squinting as much as that photo might lead you to believe. Fluorescent lights are very harsh, and I'm not a morning person.\r\n\r\n\r\n", :job => "Recently, mostly coding. Before that, writing stage and screenplays and working in television. Before that, teaching small Korean children English. Before that, school. Before that, mostly watching the Ninja Turtles, drinking juice, and falling down in parks, if memory serves.", :likes => "I'm currently reading my portfolio website, which you can check out by clicking my name in the lower left corner, and the code for this site, which you can check out by clicking the GitHub logo in the lower right corner.\r\nI recommend them both unreservedly.", :min_age => 21, :max_age => 45, :max_distance => 50, :created_at => "2014-01-16 11:56:16", :updated_at => "2014-01-16 13:15:20", :zip => 10010 },
  { :user_id => 2, :location => nil, :summary => "What, you don't know already? I used to be bigger than Jesus, you know. I still am, but I used to be as well.", :job => "I'm a house-husband.", :likes => "Grapefruit. The book and the food.", :min_age => 21, :max_age => 75, :max_distance => 50, :created_at => "2014-01-16 13:43:33", :updated_at => "2014-01-16 13:54:59", :zip => 10010 },
  { :user_id => 4, :location => nil, :summary => "- Most successful songwriter of all time by most metrics\r\n- Hair suspiciously impervious to ravages of time\r\n- Once attempted to bring eight ounces of marijuana into Japan in my personal suitcase\r\n\r\nVegetarians only, please.", :job => "Stepping into my room, finding Gideon's Bible, making sure I'm equipped with a gun, shooting off the legs of my rival, etc.", :likes => "Have you heard that Jay-Z? He has some tunes. It's all rather good, though, isn't it?", :min_age => 52, :max_age => 74, :max_distance => 50, :created_at => "2014-01-16 18:49:52", :updated_at => "2014-01-16 18:59:31", :zip => 10010 },
  { :user_id => 5, :location => nil, :summary => "Look, can you not ask me questions? I'm the quiet one.", :job => "Leave me alone.", :likes => "Don't bother me.", :min_age => 18, :max_age => 99, :max_distance => 50, :created_at => "2014-01-16 19:09:28", :updated_at => "2014-01-16 19:14:56", :zip => 10010 },
  { :user_id => 6, :location => nil, :summary => "I've got blisters on my fingers!", :job => "Octopus's gardener.", :likes => "Have you seen The Magic Christian? It's really quite underrated.", :min_age => 18, :max_age => 23, :max_distance => 50, :created_at => "2014-01-16 19:33:30", :updated_at => "2014-01-16 19:43:07", :zip => 10010 },
  { :user_id => 3, :location => nil, :summary => "I'm a smart, attractive person working at a fantastic company who is not at all susceptible to cheap flattery.", :job => "I'm browsing a website with a suspiciously high proportion of celebrity users.\r\nGreat site, though. Really well-coded.", :likes => "", :min_age => 18, :max_age => 99, :max_distance => 50, :created_at => "2014-01-16 13:23:52", :updated_at => "2014-01-16 19:47:18", :zip => 10010 }
], :without_protection => true )

Detail.create([
  { :user_id => 1, :last_on => "2014-01-16 15:38:00.872039", :height => "72", :body_type => "Average", :diet => "Anything", :smokes => "", :drinks => "Sometimes", :drugs => "", :religion => "", :sign => "", :education => "Graduate School", :job => "Computer", :offspring => "", :pets => "Likes cats", :created_at => "2014-01-16 11:56:16", :updated_at => "2014-01-16 15:38:00" },
  { :user_id => 2, :last_on => "2014-01-16 15:43:09.236415", :height => "71", :body_type => "Thin", :diet => "Anything", :smokes => "Yes", :drinks => "Often", :drugs => "Sometimes", :religion => "Other", :sign => "", :education => "Grade School", :job => "Artist", :offspring => "Has kids", :pets => "", :created_at => "2014-01-16 13:43:33", :updated_at => "2014-01-16 15:43:09" },
  { :user_id => 4, :last_on => "2014-01-16 19:03:51.876185", :height => "71", :body_type => "Thin", :diet => "Vegetarian", :smokes => "Trying to quit", :drinks => "Sometimes", :drugs => "Often", :religion => "", :sign => "", :education => "Grade School", :job => "Artist", :offspring => "Has kids", :pets => "", :created_at => "2014-01-16 18:49:52", :updated_at => "2014-01-16 19:03:51" },
  { :user_id => 5, :last_on => "2014-01-16 19:22:40.732668", :height => "70", :body_type => "", :diet => "Vegetarian", :smokes => "Yes", :drinks => "Socially", :drugs => "", :religion => "Other", :sign => "", :education => "", :job => "Retired", :offspring => "Has kids", :pets => "", :created_at => "2014-01-16 19:09:28", :updated_at => "2014-01-16 19:22:40" },
  { :user_id => 3, :last_on => "2014-01-16 19:31:15.030526", :height => "68", :body_type => "Thin", :diet => "", :smokes => "No", :drinks => "", :drugs => "", :religion => "", :sign => "Gemini", :education => "", :job => "Computer", :offspring => "", :pets => "Likes cats and dogs", :created_at => "2014-01-16 13:23:52", :updated_at => "2014-01-16 19:31:15" },
  { :user_id => 6, :last_on => "2014-01-16 19:45:39.774793", :height => "66", :body_type => "Average", :diet => "", :smokes => "Yes", :drinks => "", :drugs => "Often", :religion => "", :sign => "", :education => "High School", :job => "Hospitality", :offspring => "", :pets => "", :created_at => "2014-01-16 19:33:30", :updated_at => "2014-01-16 19:45:39" }
], :without_protection => true )

Question.create([
  { :body => "How good is your singing voice?", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :body => "Which is bigger?", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :body => "Do you like traveling?", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :body => "Are you the type of person to tell a homeless person to get a job?", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :body => "How many continents are there?", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :body => "How much can intelligence turn you on?", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :body => "Who's smarter on average?", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :body => "A \"shooting star\" is a star that...", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :body => "Which of the following do you consider to be the best explanation for the existence of human life on Earth?", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :body => "How many albums are there in your music collection?", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :body => "Imagine that you have to move somewhere far away. You'll need to pack all of your stuff and take it with you. All your things could fit nicely inside...", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" }
], :without_protection => true )

Answer.create([
  { :question_id => 1, :body => "Really awesome, actually", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Very good", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Okay", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Crappy", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 2, :body => "The earth", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :question_id => 2, :body => "The sun", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :question_id => 3, :body => "Yes", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :question_id => 3, :body => "No", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :question_id => 4, :body => "Yes", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :question_id => 4, :body => "No", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :question_id => 5, :body => "5", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "6", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "7", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "8", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 6, :body => "A lot!", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "A bit.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "Intelligence does nothing for me either way.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "Intelligence turns me off.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 7, :body => "Men", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 7, :body => "Women", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 7, :body => "Neither; they're the same on average", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 8, :body => "...burned out, and collapsed", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...collided with Earth's atmosphere", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...got sucked into a black hole", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...isn't really a star", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 9, :body => "Humans evolved from other species.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "Humans were created by a higher power.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "Humans were brought to Earth from the stars.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "I'm not sure.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 10, :body => "I have no music albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "1 to 100 albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "101 to 300 albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "301 or more albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 11, :body => "a couple of suitcases.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "a car.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "a big moving truck.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "the Black Sea.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" }
], :without_protection => true )



Conversation.create([
  { :low_user_id => 2, :high_user_id => 3, :created_at => "2014-01-16 13:54:29", :updated_at => "2014-01-16 13:54:29" },
  { :low_user_id => 1, :high_user_id => 3, :created_at => "2014-01-16 13:32:01", :updated_at => "2014-01-16 15:45:46" },
  { :low_user_id => 3, :high_user_id => 4, :created_at => "2014-01-16 19:03:37", :updated_at => "2014-01-16 19:03:37" }
], :without_protection => true )



Message.create([
  { :conversation_id => 1, :body => "I hope you're enjoying this site. Please check out my portfolio (link at bottom left) if you'd like to know more about me, or send me a message here--I check these messages regularly.", :sender_id => 1, :receiver_id => 3, :created_at => "2014-01-16 13:32:01", :updated_at => "2014-01-16 13:32:01" },
  { :conversation_id => 2, :body => "Do you know how to get me off of this thing? This is identity theft. I've been dead for 33 years; can't you people leave me alone?", :sender_id => 2, :receiver_id => 3, :created_at => "2014-01-16 13:54:29", :updated_at => "2014-01-16 13:54:29" },
  { :conversation_id => 1, :body => "I will!", :sender_id => 3, :receiver_id => 1, :created_at => "2014-01-16 19:01:06", :updated_at => "2014-01-16 19:01:06" },
  { :conversation_id => 2, :body => "Unfortunately the concept of privacy and personhood are both being eroded rather severely. I'll see what I can do.", :sender_id => 3, :receiver_id => 2, :created_at => "2014-01-16 19:01:41", :updated_at => "2014-01-16 19:01:41" },
  { :conversation_id => 3, :body => "Would you like to sing? Do you know the high harmonies to \"Maxwell's Silver Hammer\"?\r\n\r\nOh, come on. How come no one ever wants to sing that one?", :sender_id => 4, :receiver_id => 3, :created_at => "2014-01-16 19:03:37", :updated_at => "2014-01-16 19:03:37" }
], :without_protection => true )

Response.create([
  { :user_id => 3, :question_id => 1, :answer_id => 3, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:35:09", :updated_at => "2014-01-16 15:35:09" },
  { :user_id => 1, :question_id => 1, :answer_id => 2, :importance => 10, :explanation => "This answer rigorously tested at many karaoke nights.", :created_at => "2014-01-16 15:36:05", :updated_at => "2014-01-16 15:36:05" },
  { :user_id => 1, :question_id => 2, :answer_id => 6, :importance => 50, :explanation => "", :created_at => "2014-01-16 15:36:10", :updated_at => "2014-01-16 15:36:10" },
  { :user_id => 1, :question_id => 3, :answer_id => 7, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:14", :updated_at => "2014-01-16 15:36:14" },
  { :user_id => 1, :question_id => 4, :answer_id => 10, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:18", :updated_at => "2014-01-16 15:36:18" },
  { :user_id => 1, :question_id => 5, :answer_id => 13, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:23", :updated_at => "2014-01-16 15:36:23" },
  { :user_id => 1, :question_id => 6, :answer_id => 15, :importance => 50, :explanation => "", :created_at => "2014-01-16 15:36:30", :updated_at => "2014-01-16 15:36:30" },
  { :user_id => 1, :question_id => 7, :answer_id => 21, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:35", :updated_at => "2014-01-16 15:36:35" },
  { :user_id => 1, :question_id => 8, :answer_id => 25, :importance => 1, :explanation => "", :created_at => "2014-01-16 15:36:40", :updated_at => "2014-01-16 15:36:40" },
  { :user_id => 1, :question_id => 9, :answer_id => 26, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:45", :updated_at => "2014-01-16 15:36:45" },
  { :user_id => 1, :question_id => 10, :answer_id => 33, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:36:52", :updated_at => "2014-01-16 15:36:52" },
  { :user_id => 1, :question_id => 11, :answer_id => 35, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:37:00", :updated_at => "2014-01-16 15:37:00" },
  { :user_id => 3, :question_id => 5, :answer_id => 13, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:39:24", :updated_at => "2014-01-16 15:39:24" },
  { :user_id => 3, :question_id => 10, :answer_id => 31, :importance => 10, :explanation => "", :created_at => "2014-01-16 15:39:46", :updated_at => "2014-01-16 15:39:46" },
  { :user_id => 2, :question_id => 1, :answer_id => 1, :importance => 50, :explanation => "Come on, now.", :created_at => "2014-01-16 15:41:25", :updated_at => "2014-01-16 15:41:25" },
  { :user_id => 2, :question_id => 7, :answer_id => 20, :importance => 50, :explanation => "", :created_at => "2014-01-16 15:41:49", :updated_at => "2014-01-16 15:41:49" },
  { :user_id => 2, :question_id => 3, :answer_id => 8, :importance => 1, :explanation => "I did it too much when I was younger. Don't have the strength for it anymore.", :created_at => "2014-01-16 15:42:55", :updated_at => "2014-01-16 15:42:55" },
  { :user_id => 4, :question_id => 1, :answer_id => 3, :importance => 10, :explanation => "I don't need to boast", :created_at => "2014-01-16 18:52:59", :updated_at => "2014-01-16 18:52:59" },
  { :user_id => 4, :question_id => 2, :answer_id => 5, :importance => 10, :explanation => "Depends which one you're closer to, doesn't it?", :created_at => "2014-01-16 18:53:41", :updated_at => "2014-01-16 18:53:41" },
  { :user_id => 4, :question_id => 10, :answer_id => 33, :importance => 10, :explanation => "", :created_at => "2014-01-16 18:53:49", :updated_at => "2014-01-16 18:53:49" },
  { :user_id => 4, :question_id => 6, :answer_id => 16, :importance => 10, :explanation => "", :created_at => "2014-01-16 18:53:59", :updated_at => "2014-01-16 18:53:59" },
  { :user_id => 4, :question_id => 4, :answer_id => 10, :importance => 1, :explanation => "", :created_at => "2014-01-16 18:54:09", :updated_at => "2014-01-16 18:54:09" },
  { :user_id => 5, :question_id => 5, :answer_id => 13, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:13:47", :updated_at => "2014-01-16 19:13:47" },
  { :user_id => 5, :question_id => 1, :answer_id => 2, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:14:06", :updated_at => "2014-01-16 19:14:06" },
  { :user_id => 5, :question_id => 2, :answer_id => 6, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:14:11", :updated_at => "2014-01-16 19:14:11" },
  { :user_id => 5, :question_id => 3, :answer_id => 8, :importance => 50, :explanation => "", :created_at => "2014-01-16 19:14:19", :updated_at => "2014-01-16 19:14:19" },
  { :user_id => 5, :question_id => 4, :answer_id => 10, :importance => 10, :explanation => "The taxman, on the other hand...", :created_at => "2014-01-16 19:14:34", :updated_at => "2014-01-16 19:14:34" },
  { :user_id => 6, :question_id => 1, :answer_id => 3, :importance => 10, :explanation => "I'm a great singer!", :created_at => "2014-01-16 19:44:42", :updated_at => "2014-01-16 19:44:42" },
  { :user_id => 6, :question_id => 11, :answer_id => 37, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:45:01", :updated_at => "2014-01-16 19:45:01" },
  { :user_id => 6, :question_id => 4, :answer_id => 10, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:45:14", :updated_at => "2014-01-16 19:45:14" },
  { :user_id => 6, :question_id => 9, :answer_id => 28, :importance => 10, :explanation => "", :created_at => "2014-01-16 19:45:24", :updated_at => "2014-01-16 19:45:24" }
], :without_protection => true )

OkResponse.create([
  { :response_id => 1, :answer_id => 2, :created_at => "2014-01-16 15:35:09", :updated_at => "2014-01-16 15:35:09" },
  { :response_id => 1, :answer_id => 3, :created_at => "2014-01-16 15:35:09", :updated_at => "2014-01-16 15:35:09" },
  { :response_id => 2, :answer_id => 1, :created_at => "2014-01-16 15:36:05", :updated_at => "2014-01-16 15:36:05" },
  { :response_id => 2, :answer_id => 2, :created_at => "2014-01-16 15:36:05", :updated_at => "2014-01-16 15:36:05" },
  { :response_id => 2, :answer_id => 3, :created_at => "2014-01-16 15:36:05", :updated_at => "2014-01-16 15:36:05" },
  { :response_id => 3, :answer_id => 6, :created_at => "2014-01-16 15:36:10", :updated_at => "2014-01-16 15:36:10" },
  { :response_id => 4, :answer_id => 7, :created_at => "2014-01-16 15:36:14", :updated_at => "2014-01-16 15:36:14" },
  { :response_id => 5, :answer_id => 10, :created_at => "2014-01-16 15:36:18", :updated_at => "2014-01-16 15:36:18" },
  { :response_id => 6, :answer_id => 13, :created_at => "2014-01-16 15:36:23", :updated_at => "2014-01-16 15:36:23" },
  { :response_id => 7, :answer_id => 15, :created_at => "2014-01-16 15:36:30", :updated_at => "2014-01-16 15:36:30" },
  { :response_id => 7, :answer_id => 16, :created_at => "2014-01-16 15:36:30", :updated_at => "2014-01-16 15:36:30" },
  { :response_id => 8, :answer_id => 21, :created_at => "2014-01-16 15:36:35", :updated_at => "2014-01-16 15:36:35" },
  { :response_id => 9, :answer_id => 25, :created_at => "2014-01-16 15:36:40", :updated_at => "2014-01-16 15:36:40" },
  { :response_id => 10, :answer_id => 26, :created_at => "2014-01-16 15:36:45", :updated_at => "2014-01-16 15:36:45" },
  { :response_id => 11, :answer_id => 31, :created_at => "2014-01-16 15:36:52", :updated_at => "2014-01-16 15:36:52" },
  { :response_id => 11, :answer_id => 32, :created_at => "2014-01-16 15:36:52", :updated_at => "2014-01-16 15:36:52" },
  { :response_id => 11, :answer_id => 33, :created_at => "2014-01-16 15:36:52", :updated_at => "2014-01-16 15:36:52" },
  { :response_id => 12, :answer_id => 34, :created_at => "2014-01-16 15:37:00", :updated_at => "2014-01-16 15:37:00" },
  { :response_id => 12, :answer_id => 35, :created_at => "2014-01-16 15:37:00", :updated_at => "2014-01-16 15:37:00" },
  { :response_id => 12, :answer_id => 36, :created_at => "2014-01-16 15:37:00", :updated_at => "2014-01-16 15:37:00" },
  { :response_id => 13, :answer_id => 13, :created_at => "2014-01-16 15:39:24", :updated_at => "2014-01-16 15:39:24" },
  { :response_id => 14, :answer_id => 31, :created_at => "2014-01-16 15:39:46", :updated_at => "2014-01-16 15:39:46" },
  { :response_id => 14, :answer_id => 32, :created_at => "2014-01-16 15:39:46", :updated_at => "2014-01-16 15:39:46" },
  { :response_id => 15, :answer_id => 1, :created_at => "2014-01-16 15:41:25", :updated_at => "2014-01-16 15:41:25" },
  { :response_id => 16, :answer_id => 20, :created_at => "2014-01-16 15:41:49", :updated_at => "2014-01-16 15:41:49" },
  { :response_id => 17, :answer_id => 7, :created_at => "2014-01-16 15:42:55", :updated_at => "2014-01-16 15:42:55" },
  { :response_id => 17, :answer_id => 8, :created_at => "2014-01-16 15:42:55", :updated_at => "2014-01-16 15:42:55" },
  { :response_id => 18, :answer_id => 1, :created_at => "2014-01-16 18:52:59", :updated_at => "2014-01-16 18:52:59" },
  { :response_id => 18, :answer_id => 2, :created_at => "2014-01-16 18:52:59", :updated_at => "2014-01-16 18:52:59" },
  { :response_id => 18, :answer_id => 3, :created_at => "2014-01-16 18:52:59", :updated_at => "2014-01-16 18:52:59" },
  { :response_id => 18, :answer_id => 4, :created_at => "2014-01-16 18:52:59", :updated_at => "2014-01-16 18:52:59" },
  { :response_id => 19, :answer_id => 5, :created_at => "2014-01-16 18:53:41", :updated_at => "2014-01-16 18:53:41" },
  { :response_id => 20, :answer_id => 32, :created_at => "2014-01-16 18:53:49", :updated_at => "2014-01-16 18:53:49" },
  { :response_id => 20, :answer_id => 33, :created_at => "2014-01-16 18:53:49", :updated_at => "2014-01-16 18:53:49" },
  { :response_id => 21, :answer_id => 16, :created_at => "2014-01-16 18:53:59", :updated_at => "2014-01-16 18:53:59" },
  { :response_id => 21, :answer_id => 17, :created_at => "2014-01-16 18:53:59", :updated_at => "2014-01-16 18:53:59" },
  { :response_id => 22, :answer_id => 10, :created_at => "2014-01-16 18:54:09", :updated_at => "2014-01-16 18:54:09" },
  { :response_id => 23, :answer_id => 13, :created_at => "2014-01-16 19:13:47", :updated_at => "2014-01-16 19:13:47" },
  { :response_id => 24, :answer_id => 2, :created_at => "2014-01-16 19:14:06", :updated_at => "2014-01-16 19:14:06" },
  { :response_id => 24, :answer_id => 3, :created_at => "2014-01-16 19:14:06", :updated_at => "2014-01-16 19:14:06" },
  { :response_id => 25, :answer_id => 6, :created_at => "2014-01-16 19:14:11", :updated_at => "2014-01-16 19:14:11" },
  { :response_id => 26, :answer_id => 8, :created_at => "2014-01-16 19:14:19", :updated_at => "2014-01-16 19:14:19" },
  { :response_id => 27, :answer_id => 10, :created_at => "2014-01-16 19:14:34", :updated_at => "2014-01-16 19:14:34" },
  { :response_id => 28, :answer_id => 3, :created_at => "2014-01-16 19:44:42", :updated_at => "2014-01-16 19:44:42" },
  { :response_id => 28, :answer_id => 4, :created_at => "2014-01-16 19:44:42", :updated_at => "2014-01-16 19:44:42" },
  { :response_id => 29, :answer_id => 36, :created_at => "2014-01-16 19:45:01", :updated_at => "2014-01-16 19:45:01" },
  { :response_id => 29, :answer_id => 37, :created_at => "2014-01-16 19:45:02", :updated_at => "2014-01-16 19:45:02" },
  { :response_id => 30, :answer_id => 9, :created_at => "2014-01-16 19:45:14", :updated_at => "2014-01-16 19:45:14" },
  { :response_id => 30, :answer_id => 10, :created_at => "2014-01-16 19:45:14", :updated_at => "2014-01-16 19:45:14" },
  { :response_id => 31, :answer_id => 28, :created_at => "2014-01-16 19:45:24", :updated_at => "2014-01-16 19:45:24" }
], :without_protection => true )


Visit.create([
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:26:21", :updated_at => "2014-01-16 15:26:21" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:27:51", :updated_at => "2014-01-16 15:27:51" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:29:42", :updated_at => "2014-01-16 15:29:42" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:29:58", :updated_at => "2014-01-16 15:29:58" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:32:40", :updated_at => "2014-01-16 15:32:40" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:33:56", :updated_at => "2014-01-16 15:33:56" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:34:22", :updated_at => "2014-01-16 15:34:22" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 15:38:57", :updated_at => "2014-01-16 15:38:57" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 15:39:28", :updated_at => "2014-01-16 15:39:28" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 15:39:49", :updated_at => "2014-01-16 15:39:49" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:40:02", :updated_at => "2014-01-16 15:40:02" },
  { :visitee_id => 3, :visitor_id => 2, :created_at => "2014-01-16 15:41:34", :updated_at => "2014-01-16 15:41:34" },
  { :visitee_id => 1, :visitor_id => 2, :created_at => "2014-01-16 15:41:38", :updated_at => "2014-01-16 15:41:38" },
  { :visitee_id => 1, :visitor_id => 2, :created_at => "2014-01-16 15:42:31", :updated_at => "2014-01-16 15:42:31" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 15:44:41", :updated_at => "2014-01-16 15:44:41" },
  { :visitee_id => 2, :visitor_id => 3, :created_at => "2014-01-16 15:44:51", :updated_at => "2014-01-16 15:44:51" },
  { :visitee_id => 1, :visitor_id => 4, :created_at => "2014-01-16 18:53:06", :updated_at => "2014-01-16 18:53:06" },
  { :visitee_id => 2, :visitor_id => 4, :created_at => "2014-01-16 18:53:09", :updated_at => "2014-01-16 18:53:09" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 18:53:12", :updated_at => "2014-01-16 18:53:12" },
  { :visitee_id => 1, :visitor_id => 4, :created_at => "2014-01-16 18:53:19", :updated_at => "2014-01-16 18:53:19" },
  { :visitee_id => 1, :visitor_id => 4, :created_at => "2014-01-16 18:54:16", :updated_at => "2014-01-16 18:54:16" },
  { :visitee_id => 4, :visitor_id => 3, :created_at => "2014-01-16 19:00:10", :updated_at => "2014-01-16 19:00:10" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 19:02:31", :updated_at => "2014-01-16 19:02:31" },
  { :visitee_id => 3, :visitor_id => 5, :created_at => "2014-01-16 19:13:37", :updated_at => "2014-01-16 19:13:37" },
  { :visitee_id => 3, :visitor_id => 5, :created_at => "2014-01-16 19:22:16", :updated_at => "2014-01-16 19:22:16" },
  { :visitee_id => 1, :visitor_id => 5, :created_at => "2014-01-16 19:22:25", :updated_at => "2014-01-16 19:22:25" },
  { :visitee_id => 2, :visitor_id => 5, :created_at => "2014-01-16 19:22:28", :updated_at => "2014-01-16 19:22:28" },
  { :visitee_id => 3, :visitor_id => 5, :created_at => "2014-01-16 19:22:31", :updated_at => "2014-01-16 19:22:31" },
  { :visitee_id => 4, :visitor_id => 5, :created_at => "2014-01-16 19:22:33", :updated_at => "2014-01-16 19:22:33" },
  { :visitee_id => 5, :visitor_id => 3, :created_at => "2014-01-16 19:28:14", :updated_at => "2014-01-16 19:28:14" },
  { :visitee_id => 5, :visitor_id => 3, :created_at => "2014-01-16 19:30:23", :updated_at => "2014-01-16 19:30:23" },
  { :visitee_id => 5, :visitor_id => 3, :created_at => "2014-01-16 19:30:36", :updated_at => "2014-01-16 19:30:36" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 19:30:43", :updated_at => "2014-01-16 19:30:43" },
  { :visitee_id => 1, :visitor_id => 6, :created_at => "2014-01-16 19:43:19", :updated_at => "2014-01-16 19:43:19" },
  { :visitee_id => 2, :visitor_id => 6, :created_at => "2014-01-16 19:43:21", :updated_at => "2014-01-16 19:43:21" },
  { :visitee_id => 3, :visitor_id => 6, :created_at => "2014-01-16 19:43:23", :updated_at => "2014-01-16 19:43:23" },
  { :visitee_id => 4, :visitor_id => 6, :created_at => "2014-01-16 19:43:25", :updated_at => "2014-01-16 19:43:25" },
  { :visitee_id => 5, :visitor_id => 6, :created_at => "2014-01-16 19:43:27", :updated_at => "2014-01-16 19:43:27" },
  { :visitee_id => 1, :visitor_id => 6, :created_at => "2014-01-16 19:44:47", :updated_at => "2014-01-16 19:44:47" },
  { :visitee_id => 6, :visitor_id => 3, :created_at => "2014-01-16 19:47:26", :updated_at => "2014-01-16 19:47:26" }
], :without_protection => true )


