# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Answer.create([
  { :question_id => 1, :body => "Really awesome, actually", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Very good", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Okay", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 1, :body => "Crappy", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :question_id => 2, :body => "The earth", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :question_id => 2, :body => "The sun", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :question_id => 3, :body => "Yes", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :question_id => 3, :body => "No", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :question_id => 4, :body => "Yes", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :question_id => 4, :body => "No", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :question_id => 5, :body => "5", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "6", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "7", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 5, :body => "8", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :question_id => 6, :body => "A lot!", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "A bit.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "Intelligence does nothing for me either way.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 6, :body => "Intelligence turns me off.", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :question_id => 7, :body => "Men", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 7, :body => "Women", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 7, :body => "Neither; they're the same on average", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :question_id => 8, :body => "...burned out, and collapsed", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...collided with Earth's atmosphere", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...got sucked into a black hole", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 8, :body => "...isn't really a star", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :question_id => 9, :body => "Humans evolved from other species.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "Humans were created by a higher power.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "Humans were brought to Earth from the stars.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 9, :body => "I'm not sure.", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :question_id => 10, :body => "I have no music albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "1 to 100 albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "101 to 300 albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 10, :body => "301 or more albums.", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :question_id => 11, :body => "a couple of suitcases.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "a car.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "a big moving truck.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" },
  { :question_id => 11, :body => "the Black Sea.", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" }
], :without_protection => true )



Conversation.create([
  { :low_user_id => 1, :high_user_id => 3, :created_at => "2014-01-16 13:32:01", :updated_at => "2014-01-16 13:32:01" },
  { :low_user_id => 3, :high_user_id => 4, :created_at => "2014-01-16 13:54:29", :updated_at => "2014-01-16 13:54:29" }
], :without_protection => true )



Detail.create([
  { :user_id => 1, :last_on => "2014-01-16 13:34:16.487781", :height => "72", :body_type => "Average", :diet => "Anything", :smokes => "", :drinks => "Sometimes", :drugs => "", :religion => "", :sign => "", :education => "Graduate School", :job => "Computer", :offspring => "", :pets => "Likes cats", :created_at => "2014-01-16 11:56:16", :updated_at => "2014-01-16 13:34:16" },
  { :user_id => 3, :last_on => "2014-01-16 13:41:02.138523", :height => "68", :body_type => "Thin", :diet => "", :smokes => "No", :drinks => "", :drugs => "", :religion => "", :sign => "Gemini", :education => "", :job => "Computer", :offspring => "", :pets => "Likes cats and dogs", :created_at => "2014-01-16 13:23:52", :updated_at => "2014-01-16 13:41:02" },
  { :user_id => 4, :last_on => "2014-01-16 13:55:03.610947", :height => "71", :body_type => "Thin", :diet => "Anything", :smokes => "Yes", :drinks => "Often", :drugs => "Sometimes", :religion => "Other", :sign => "", :education => "Grade School", :job => "Artist", :offspring => "Has kids", :pets => "", :created_at => "2014-01-16 13:43:33", :updated_at => "2014-01-16 13:55:03" }
], :without_protection => true )



Message.create([
  { :conversation_id => 1, :body => "I hope you're enjoying this site. Please check out my portfolio (link at bottom left) if you'd like to know more about me, or send me a message here--I check these messages regularly.", :sender_id => 1, :receiver_id => 3, :created_at => "2014-01-16 13:32:01", :updated_at => "2014-01-16 13:32:01" },
  { :conversation_id => 2, :body => "Do you know how to get me off of this thing? This is identity theft. I've been dead for 33 years; can't you people leave me alone?", :sender_id => 4, :receiver_id => 3, :created_at => "2014-01-16 13:54:29", :updated_at => "2014-01-16 13:54:29" }
], :without_protection => true )



OkResponse.create([
  { :response_id => 1, :answer_id => 1, :created_at => "2014-01-16 13:03:46", :updated_at => "2014-01-16 13:03:46" },
  { :response_id => 1, :answer_id => 2, :created_at => "2014-01-16 13:03:46", :updated_at => "2014-01-16 13:03:46" },
  { :response_id => 1, :answer_id => 3, :created_at => "2014-01-16 13:03:46", :updated_at => "2014-01-16 13:03:46" },
  { :response_id => 3, :answer_id => 7, :created_at => "2014-01-16 13:03:59", :updated_at => "2014-01-16 13:03:59" },
  { :response_id => 4, :answer_id => 10, :created_at => "2014-01-16 13:04:04", :updated_at => "2014-01-16 13:04:04" },
  { :response_id => 5, :answer_id => 13, :created_at => "2014-01-16 13:06:42", :updated_at => "2014-01-16 13:06:42" },
  { :response_id => 6, :answer_id => 15, :created_at => "2014-01-16 13:06:51", :updated_at => "2014-01-16 13:06:51" },
  { :response_id => 6, :answer_id => 16, :created_at => "2014-01-16 13:06:51", :updated_at => "2014-01-16 13:06:51" },
  { :response_id => 7, :answer_id => 21, :created_at => "2014-01-16 13:11:58", :updated_at => "2014-01-16 13:11:58" },
  { :response_id => 8, :answer_id => 25, :created_at => "2014-01-16 13:12:50", :updated_at => "2014-01-16 13:12:50" },
  { :response_id => 9, :answer_id => 26, :created_at => "2014-01-16 13:12:57", :updated_at => "2014-01-16 13:12:57" },
  { :response_id => 10, :answer_id => 31, :created_at => "2014-01-16 13:13:12", :updated_at => "2014-01-16 13:13:12" },
  { :response_id => 10, :answer_id => 32, :created_at => "2014-01-16 13:13:12", :updated_at => "2014-01-16 13:13:12" },
  { :response_id => 10, :answer_id => 33, :created_at => "2014-01-16 13:13:12", :updated_at => "2014-01-16 13:13:12" },
  { :response_id => 11, :answer_id => 34, :created_at => "2014-01-16 13:14:19", :updated_at => "2014-01-16 13:14:19" },
  { :response_id => 11, :answer_id => 35, :created_at => "2014-01-16 13:14:19", :updated_at => "2014-01-16 13:14:19" },
  { :response_id => 11, :answer_id => 36, :created_at => "2014-01-16 13:14:19", :updated_at => "2014-01-16 13:14:19" },
  { :response_id => 12, :answer_id => 13, :created_at => "2014-01-16 13:28:24", :updated_at => "2014-01-16 13:28:24" },
  { :response_id => 13, :answer_id => 28, :created_at => "2014-01-16 13:28:46", :updated_at => "2014-01-16 13:28:46" },
  { :response_id => 13, :answer_id => 29, :created_at => "2014-01-16 13:28:46", :updated_at => "2014-01-16 13:28:46" },
  { :response_id => 14, :answer_id => 6, :created_at => "2014-01-16 13:29:19", :updated_at => "2014-01-16 13:29:19" },
  { :response_id => 2, :answer_id => 6, :created_at => "2014-01-16 13:30:04", :updated_at => "2014-01-16 13:30:04" },
  { :response_id => 15, :answer_id => 1, :created_at => "2014-01-16 13:48:44", :updated_at => "2014-01-16 13:48:44" },
  { :response_id => 16, :answer_id => 5, :created_at => "2014-01-16 13:48:53", :updated_at => "2014-01-16 13:48:53" },
  { :response_id => 16, :answer_id => 6, :created_at => "2014-01-16 13:48:53", :updated_at => "2014-01-16 13:48:53" },
  { :response_id => 17, :answer_id => 8, :created_at => "2014-01-16 13:49:15", :updated_at => "2014-01-16 13:49:15" },
  { :response_id => 18, :answer_id => 26, :created_at => "2014-01-16 13:49:39", :updated_at => "2014-01-16 13:49:39" },
  { :response_id => 18, :answer_id => 27, :created_at => "2014-01-16 13:49:39", :updated_at => "2014-01-16 13:49:39" },
  { :response_id => 18, :answer_id => 28, :created_at => "2014-01-16 13:49:39", :updated_at => "2014-01-16 13:49:39" },
  { :response_id => 18, :answer_id => 29, :created_at => "2014-01-16 13:49:39", :updated_at => "2014-01-16 13:49:39" }
], :without_protection => true )



Profile.create([
  { :user_id => 1, :location => nil, :summary => "I'm a web developer who you are hopefully about to hire. I created this site. Things I like in addition to coding include but are by no means limited to ineptly playing the guitar, cats, improvisational and stand-up comedy, the NBA (go Raptors), Korean BBQ, scuba diving, the works of William Gibson, and haphazardly chosen lists.\r\n\r\nI am generally not squinting as much as that photo might lead you to believe. Fluorescent lights are very harsh, and I'm not a morning person.\r\n\r\n\r\n", :job => "Recently, mostly coding. Before that, writing stage and screenplays and working in television. Before that, teaching small Korean children English. Before that, school. Before that, mostly watching the Ninja Turtles, drinking juice, and falling down in parks, if memory serves.", :likes => "I'm currently reading my portfolio website, which you can check out by clicking my name in the lower left corner, and the code for this site, which you can check out by clicking the GitHub logo in the lower right corner.\r\nI recommend them both unreservedly.", :min_age => 21, :max_age => 45, :max_distance => 50, :created_at => "2014-01-16 11:56:16", :updated_at => "2014-01-16 13:15:20", :zip => 10010 },
  { :user_id => 3, :location => nil, :summary => "", :job => "", :likes => "", :min_age => 18, :max_age => 99, :max_distance => 50, :created_at => "2014-01-16 13:23:52", :updated_at => "2014-01-16 13:23:52", :zip => 10010 },
  { :user_id => 4, :location => nil, :summary => "What, you don't know already? I used to be bigger than Jesus, you know. I still am, but I used to be as well.", :job => "I'm a house-husband.", :likes => "Grapefruit. The book and the food.", :min_age => 21, :max_age => 75, :max_distance => 50, :created_at => "2014-01-16 13:43:33", :updated_at => "2014-01-16 13:54:59", :zip => 10010 }
], :without_protection => true )



Question.create([
  { :body => "How good is your singing voice?", :created_at => "2014-01-16 13:01:51", :updated_at => "2014-01-16 13:01:51" },
  { :body => "Which is bigger?", :created_at => "2014-01-16 13:02:20", :updated_at => "2014-01-16 13:02:20" },
  { :body => "Do you like traveling?", :created_at => "2014-01-16 13:02:51", :updated_at => "2014-01-16 13:02:51" },
  { :body => "Are you the type of person to tell a homeless person to get a job?", :created_at => "2014-01-16 13:03:20", :updated_at => "2014-01-16 13:03:20" },
  { :body => "How many continents are there?", :created_at => "2014-01-16 13:04:29", :updated_at => "2014-01-16 13:04:29" },
  { :body => "How much can intelligence turn you on?", :created_at => "2014-01-16 13:05:48", :updated_at => "2014-01-16 13:05:48" },
  { :body => "Who's smarter on average?", :created_at => "2014-01-16 13:08:30", :updated_at => "2014-01-16 13:08:30" },
  { :body => "A \"shooting star\" is a star that...", :created_at => "2014-01-16 13:09:25", :updated_at => "2014-01-16 13:09:25" },
  { :body => "Which of the following do you consider to be the best explanation for the existence of human life on Earth?", :created_at => "2014-01-16 13:10:08", :updated_at => "2014-01-16 13:10:08" },
  { :body => "How many albums are there in your music collection?", :created_at => "2014-01-16 13:11:09", :updated_at => "2014-01-16 13:11:09" },
  { :body => "Imagine that you have to move somewhere far away. You'll need to pack all of your stuff and take it with you. All your things could fit nicely inside...", :created_at => "2014-01-16 13:14:09", :updated_at => "2014-01-16 13:14:09" }
], :without_protection => true )



Response.create([
  { :user_id => 1, :question_id => 3, :answer_id => 7, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:03:59", :updated_at => "2014-01-16 13:03:59" },
  { :user_id => 1, :question_id => 4, :answer_id => 10, :importance => 50, :explanation => "", :created_at => "2014-01-16 13:04:04", :updated_at => "2014-01-16 13:04:04" },
  { :user_id => 1, :question_id => 5, :answer_id => 13, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:06:42", :updated_at => "2014-01-16 13:06:42" },
  { :user_id => 1, :question_id => 6, :answer_id => 15, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:06:51", :updated_at => "2014-01-16 13:06:51" },
  { :user_id => 1, :question_id => 7, :answer_id => 21, :importance => 50, :explanation => "", :created_at => "2014-01-16 13:11:58", :updated_at => "2014-01-16 13:11:58" },
  { :user_id => 1, :question_id => 1, :answer_id => 2, :importance => 10, :explanation => "This answer verified scientifically with rigorous karaoke-based testing.", :created_at => "2014-01-16 13:03:46", :updated_at => "2014-01-16 13:12:28" },
  { :user_id => 1, :question_id => 8, :answer_id => 25, :importance => 1, :explanation => "", :created_at => "2014-01-16 13:12:50", :updated_at => "2014-01-16 13:12:50" },
  { :user_id => 1, :question_id => 9, :answer_id => 26, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:12:57", :updated_at => "2014-01-16 13:12:57" },
  { :user_id => 1, :question_id => 10, :answer_id => 33, :importance => 1, :explanation => "", :created_at => "2014-01-16 13:13:12", :updated_at => "2014-01-16 13:13:12" },
  { :user_id => 1, :question_id => 11, :answer_id => 35, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:14:19", :updated_at => "2014-01-16 13:14:19" },
  { :user_id => 3, :question_id => 5, :answer_id => 13, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:28:24", :updated_at => "2014-01-16 13:28:24" },
  { :user_id => 3, :question_id => 9, :answer_id => 28, :importance => 1, :explanation => "", :created_at => "2014-01-16 13:28:46", :updated_at => "2014-01-16 13:28:46" },
  { :user_id => 3, :question_id => 2, :answer_id => 6, :importance => 10, :explanation => "", :created_at => "2014-01-16 13:29:19", :updated_at => "2014-01-16 13:29:19" },
  { :user_id => 1, :question_id => 2, :answer_id => 6, :importance => 50, :explanation => "", :created_at => "2014-01-16 13:03:54", :updated_at => "2014-01-16 13:30:04" },
  { :user_id => 4, :question_id => 1, :answer_id => 1, :importance => 50, :explanation => "", :created_at => "2014-01-16 13:48:44", :updated_at => "2014-01-16 13:48:44" },
  { :user_id => 4, :question_id => 2, :answer_id => 6, :importance => 0, :explanation => "", :created_at => "2014-01-16 13:48:53", :updated_at => "2014-01-16 13:48:53" },
  { :user_id => 4, :question_id => 3, :answer_id => 8, :importance => 10, :explanation => "Traveled too much when I was younger. Don't have the stomach for it anymore.", :created_at => "2014-01-16 13:49:15", :updated_at => "2014-01-16 13:49:15" },
  { :user_id => 4, :question_id => 9, :answer_id => 28, :importance => 50, :explanation => "", :created_at => "2014-01-16 13:49:39", :updated_at => "2014-01-16 13:49:39" }
], :without_protection => true )



User.create([
  { :name => "KiranHelferty", :password_digest => "$2a$10$Os2jkkG2IKGLKReKTt//eOgibYWMF.UaJkLczfD622gorFkR1oIz2", :token => "22x_8XkW8i6FkcQvq4CZLQ", :created_at => "2014-01-16 11:56:15", :updated_at => "2014-01-16 13:34:30", :gender => "M", :orientation => "Straight", :age => 28, :photo_file_name => "kiran-helferty.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 121838, :photo_updated_at => "2014-01-16 11:56:13", :latitude => 40.811164, :longitude => -73.952539, :address => "301 Saint Nicholas Avenue, New York, NY 10027, USA" },
  { :name => "MeanMrMustard", :password_digest => "$2a$10$dIS9tR3u3ARU..ANicOixew3d40yflMdGtJiVHnl4Iu8a6oPv/WCG", :token => "I0C4n6I9SpQCoWd21jG6eg", :created_at => "2014-01-16 13:43:32", :updated_at => "2014-01-16 13:55:04", :gender => "M", :orientation => "Straight", :age => 73, :photo_file_name => "lennon.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 98127, :photo_updated_at => "2014-01-16 13:43:29", :latitude => 40.776012, :longitude => -73.969595, :address => "271 W 71st St, New York, NY 10023, USA" },
  { :name => "ProspectiveEmployer", :password_digest => "$2a$10$ZYigIbW2zIfwjpCkd3S0cOJCh4SqM3jM/i8q75WQ0NtiUzb.BHCoq", :token => "EO26AZfVZNdELPBjTKccqg", :created_at => "2014-01-16 13:23:51", :updated_at => "2014-01-16 13:55:12", :gender => "F", :orientation => "Bisexual", :age => 30, :photo_file_name => "master-COOP354.jpg", :photo_content_type => "image/jpeg", :photo_file_size => 421098, :photo_updated_at => "2014-01-16 13:23:48", :latitude => 40.7308586, :longitude => -73.9921875, :address => "756-770 Broadway, New York, NY 10003, USA" }
], :without_protection => true )



Visit.create([
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:24:01", :updated_at => "2014-01-16 13:24:01" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:28:08", :updated_at => "2014-01-16 13:28:08" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:28:28", :updated_at => "2014-01-16 13:28:28" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:28:48", :updated_at => "2014-01-16 13:28:48" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:29:21", :updated_at => "2014-01-16 13:29:21" },
  { :visitee_id => 3, :visitor_id => 1, :created_at => "2014-01-16 13:29:54", :updated_at => "2014-01-16 13:29:54" },
  { :visitee_id => 3, :visitor_id => 1, :created_at => "2014-01-16 13:30:07", :updated_at => "2014-01-16 13:30:07" },
  { :visitee_id => 3, :visitor_id => 1, :created_at => "2014-01-16 13:30:24", :updated_at => "2014-01-16 13:30:24" },
  { :visitee_id => 1, :visitor_id => 3, :created_at => "2014-01-16 13:40:07", :updated_at => "2014-01-16 13:40:07" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 13:49:24", :updated_at => "2014-01-16 13:49:24" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 13:49:41", :updated_at => "2014-01-16 13:49:41" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 13:51:54", :updated_at => "2014-01-16 13:51:54" },
  { :visitee_id => 3, :visitor_id => 4, :created_at => "2014-01-16 13:52:44", :updated_at => "2014-01-16 13:52:44" },
  { :visitee_id => 4, :visitor_id => 3, :created_at => "2014-01-16 13:55:31", :updated_at => "2014-01-16 13:55:31" }
], :without_protection => true )


